# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
    """The  service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SumNumbers = channel.unary_unary(
                '/calculator.Calculator/SumNumbers',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.NumericResult.FromString,
                )
        self.SubtractNumbers = channel.unary_unary(
                '/calculator.Calculator/SubtractNumbers',
                request_serializer=calculator__pb2.CalcRequest.SerializeToString,
                response_deserializer=calculator__pb2.NumericResult.FromString,
                )


class CalculatorServicer(object):
    """The  service definition.
    """

    def SumNumbers(self, request, context):
        """Defines the Remote Procedure Calls available on the Service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubtractNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SumNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.SumNumbers,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.NumericResult.SerializeToString,
            ),
            'SubtractNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.SubtractNumbers,
                    request_deserializer=calculator__pb2.CalcRequest.FromString,
                    response_serializer=calculator__pb2.NumericResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """The  service definition.
    """

    @staticmethod
    def SumNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/SumNumbers',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.NumericResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubtractNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/SubtractNumbers',
            calculator__pb2.CalcRequest.SerializeToString,
            calculator__pb2.NumericResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
