# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainer/dummy_trainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btrainer/dummy_trainer.proto\x12\rdummy_trainer\"&\n\x11StartTrainRequest\x12\x11\n\tdata_path\x18\x01 \x01(\t\"\xa5\x02\n\rTrainResponse\x12;\n\x0estart_response\x18\x01 \x01(\x0b\x32!.dummy_trainer.TrainStartResponseH\x00\x12\x41\n\x11progress_response\x18\x02 \x01(\x0b\x32$.dummy_trainer.TrainProgressResponseH\x00\x12;\n\x0e\x65rror_response\x18\x03 \x01(\x0b\x32!.dummy_trainer.TrainErrorResponseH\x00\x12\x45\n\x13\x63ompletion_response\x18\x04 \x01(\x0b\x32&.dummy_trainer.TrainCompletionResponseH\x00\x42\x10\n\x0eresponse_types\"%\n\x12TrainStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x15TrainProgressResponse\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\"\x98\x01\n\x12TrainErrorResponse\x12?\n\nerror_type\x18\x01 \x01(\x0e\x32+.dummy_trainer.TrainErrorResponse.ErrorType\x12\x15\n\rerror_message\x18\x02 \x01(\t\"*\n\tErrorType\x12\x12\n\x0e\x44\x41TA_NOT_FOUND\x10\x00\x12\t\n\x05OTHER\x10\x63\"-\n\x17TrainCompletionResponse\x12\x12\n\nmodel_path\x18\x01 \x01(\t2^\n\x0c\x44ummyTrainer\x12N\n\nStartTrain\x12 .dummy_trainer.StartTrainRequest\x1a\x1c.dummy_trainer.TrainResponse0\x01\x62\x06proto3')



_STARTTRAINREQUEST = DESCRIPTOR.message_types_by_name['StartTrainRequest']
_TRAINRESPONSE = DESCRIPTOR.message_types_by_name['TrainResponse']
_TRAINSTARTRESPONSE = DESCRIPTOR.message_types_by_name['TrainStartResponse']
_TRAINPROGRESSRESPONSE = DESCRIPTOR.message_types_by_name['TrainProgressResponse']
_TRAINERRORRESPONSE = DESCRIPTOR.message_types_by_name['TrainErrorResponse']
_TRAINCOMPLETIONRESPONSE = DESCRIPTOR.message_types_by_name['TrainCompletionResponse']
_TRAINERRORRESPONSE_ERRORTYPE = _TRAINERRORRESPONSE.enum_types_by_name['ErrorType']
StartTrainRequest = _reflection.GeneratedProtocolMessageType('StartTrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTTRAINREQUEST,
  '__module__' : 'trainer.dummy_trainer_pb2'
  # @@protoc_insertion_point(class_scope:dummy_trainer.StartTrainRequest)
  })
_sym_db.RegisterMessage(StartTrainRequest)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'trainer.dummy_trainer_pb2'
  # @@protoc_insertion_point(class_scope:dummy_trainer.TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

TrainStartResponse = _reflection.GeneratedProtocolMessageType('TrainStartResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINSTARTRESPONSE,
  '__module__' : 'trainer.dummy_trainer_pb2'
  # @@protoc_insertion_point(class_scope:dummy_trainer.TrainStartResponse)
  })
_sym_db.RegisterMessage(TrainStartResponse)

TrainProgressResponse = _reflection.GeneratedProtocolMessageType('TrainProgressResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINPROGRESSRESPONSE,
  '__module__' : 'trainer.dummy_trainer_pb2'
  # @@protoc_insertion_point(class_scope:dummy_trainer.TrainProgressResponse)
  })
_sym_db.RegisterMessage(TrainProgressResponse)

TrainErrorResponse = _reflection.GeneratedProtocolMessageType('TrainErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINERRORRESPONSE,
  '__module__' : 'trainer.dummy_trainer_pb2'
  # @@protoc_insertion_point(class_scope:dummy_trainer.TrainErrorResponse)
  })
_sym_db.RegisterMessage(TrainErrorResponse)

TrainCompletionResponse = _reflection.GeneratedProtocolMessageType('TrainCompletionResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINCOMPLETIONRESPONSE,
  '__module__' : 'trainer.dummy_trainer_pb2'
  # @@protoc_insertion_point(class_scope:dummy_trainer.TrainCompletionResponse)
  })
_sym_db.RegisterMessage(TrainCompletionResponse)

_DUMMYTRAINER = DESCRIPTOR.services_by_name['DummyTrainer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTTRAINREQUEST._serialized_start=46
  _STARTTRAINREQUEST._serialized_end=84
  _TRAINRESPONSE._serialized_start=87
  _TRAINRESPONSE._serialized_end=380
  _TRAINSTARTRESPONSE._serialized_start=382
  _TRAINSTARTRESPONSE._serialized_end=419
  _TRAINPROGRESSRESPONSE._serialized_start=421
  _TRAINPROGRESSRESPONSE._serialized_end=459
  _TRAINERRORRESPONSE._serialized_start=462
  _TRAINERRORRESPONSE._serialized_end=614
  _TRAINERRORRESPONSE_ERRORTYPE._serialized_start=572
  _TRAINERRORRESPONSE_ERRORTYPE._serialized_end=614
  _TRAINCOMPLETIONRESPONSE._serialized_start=616
  _TRAINCOMPLETIONRESPONSE._serialized_end=661
  _DUMMYTRAINER._serialized_start=663
  _DUMMYTRAINER._serialized_end=757
# @@protoc_insertion_point(module_scope)
