# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from trainer import dummy_trainer_pb2 as trainer_dot_dummy__trainer__pb2


class DummyTrainerStub(object):
    """The  service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTrain = channel.unary_stream(
                '/dummy_trainer.DummyTrainer/StartTrain',
                request_serializer=trainer_dot_dummy__trainer__pb2.StartTrainRequest.SerializeToString,
                response_deserializer=trainer_dot_dummy__trainer__pb2.TrainResponse.FromString,
                )


class DummyTrainerServicer(object):
    """The  service definition.
    """

    def StartTrain(self, request, context):
        """Defines the Remote Procedure Calls available on the Service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DummyTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTrain': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTrain,
                    request_deserializer=trainer_dot_dummy__trainer__pb2.StartTrainRequest.FromString,
                    response_serializer=trainer_dot_dummy__trainer__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummy_trainer.DummyTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DummyTrainer(object):
    """The  service definition.
    """

    @staticmethod
    def StartTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dummy_trainer.DummyTrainer/StartTrain',
            trainer_dot_dummy__trainer__pb2.StartTrainRequest.SerializeToString,
            trainer_dot_dummy__trainer__pb2.TrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
